version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4

    volumes:
      - /opt/compose/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /opt/compose/kibana/kibana.perceive.internal.key:/opt/kibana.perceive.internal.key
      - /opt/compose/kibana/kibana.perceive.internal.cer:/opt/kibana.perceive.internal.cer

    ports:
      - 5601:5601

    environment:
      SERVER_NAME: kibana.perceive.internal
      ELASTICSEARCH_URL: http://{ELASTIC_IP}:9200