version: '2'
services:
  nifi:
    build:
      context: .
      dockerfile: Dockerfile-alternate

    volumes:
      - /opt/compose/nifi/flow.xml.gz:/opt/nifi/nifi-1.6.0/conf/flow.xml.gz

    ports:
      - 8080:8080
