---
- name: "Configure Confluent"
  hosts: "confluent-servers"
  become: True

  tasks:
    - name: Create topics
      command: docker exec confluent_broker_1 kafka-topics --create --topic logs_windows --partitions 1 --replication-factor 1 --if-not-exists --zookeeper {{inventory_hostname}}:2181
