---
- name: "Deploy Nifi container"
  hosts: "nifi-servers"
  become: True

  tasks:
    - name: Create main directory
      file:
        path: /opt/compose/nifi
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: yes

    - name: Create cert directory
      file:
        path: /opt/certs
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: yes

    - name: Copy docker settings to remote
      copy:
        src: ../nifi/docker-compose.yml
        dest: /opt/compose/nifi/docker-compose.yml
        owner: root
        group: root
        mode: 0755

    - name: Copy Dockerfile to remote
      copy:
        src: ../nifi/Dockerfile-nifi
        dest: /opt/compose/nifi/Dockerfile-nifi
        owner: root
        group: root
        mode: 0755

    - name: Copy flow config to remote
      copy:
        src: ../nifi/flow.xml
        dest: /tmp/flow.xml
        owner: root
        group: root
        mode: 0755

    - name: Copy keystore to remote
      copy:
        src: ../keystore.jks
        dest: /opt/certs/keystore.jks
        owner: root
        group: root
        mode: 0755

    - name: Copy truststore to remote
      copy:
        src: ../truststore.jks
        dest: /opt/certs/truststore.jks
        owner: root
        group: root
        mode: 0755

    - name: Compress flowfile
      archive:
        path: /tmp/flow.xml
        dest: /opt/compose/nifi/flow.xml.gz
        mode: 0755

    - name: Run the service defined in docker-compose.yml
      docker_service:
        project_src: /opt/compose/nifi